[build-system]
requires = ["setuptools", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "MRArbGrad"
version = "5.1.3"
dependencies = ["numpy"]
requires-python = ">=3.10"

description = "Non-Cartesian MRI Gradient Waveform Toolbox (MRArbGrad)"
keywords = ["mri", "pulse-sequence", "gradient-waveform", "trajectory", "non-Cartesian", "real-time"]
authors = [{name = "Rui Luo", email = "Rui.1002@proton.me"}]

license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"

[project.urls]
Repository = "https://github.com/RyanShanghaitech/MRArbGrad"
Examples = "https://github.com/RyanShanghaitech/MRArbGrad/tree/main/example"
